
apiVersion: apps/v1
kind: Deployment
metadata:
  name: khushi-deployment
  labels:
    app: khushi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: khushi
  template:
    metadata:
      labels:
        app: khushi
    spec:
      containers:
      - name: khushi
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-computers:663bd8a79e2ae3f9e420d9e2218027715886dc43
        ports:
        - containerPort: 80
