
apiVersion: apps/v1
kind: Deployment
metadata:
  name: khushi-deployment
  labels:
    app: khushi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: khushi
  template:
    metadata:
      labels:
        app: khushi
    spec:
      containers:
      - name: khushi
        image: 049061799945.dkr.ecr.ap-southeast-2.amazonaws.com/shopping-site-khushi:089ae27783dce6f7bcd7c74f27d3c34f0cf5ff79
        ports:
        - containerPort: 80
