
apiVersion: apps/v1
kind: Deployment
metadata:
  name: khushi-deployment
  labels:
    app: khushi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: khushi
  template:
    metadata:
      labels:
        app: khushi
    spec:
      containers:
      - name: khushi
        image: 049061799945.dkr.ecr.ap-southeast-2.amazonaws.com/shopping-site-khushi:d42dfc55f0a8115a6a5dd6ab65d72609bee165f6
        ports:
        - containerPort: 80
