
apiVersion: apps/v1
kind: Deployment
metadata:
  name: khushi-deployment
  labels:
    app: khushi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: khushi
  template:
    metadata:
      labels:
        app: khushi
    spec:
      containers:
      - name: khushi
        image: 049061799945.dkr.ecr.ap-southeast-2.amazonaws.com/shopping-site-khushi:46147004db3092d066255d59f75f09be9bf82505
        ports:
        - containerPort: 80
